name: Booklib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: ancelotow
        uses: docker/login-action@v1
        with:
          username: ancelotow
          password: 6a7c170d-104c-4da0-92be-3eb4b693f596
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ./mvnw package && ancelotow/booklib:latest
